===== Python'da Metin ile Çalışmak =====

== 1.Metin uzunluğu bulmak ==
<code python>
>>> text1 = "Yurt dışında yaşayan vatandaşlarımız, daha önce zahmetli ve uzun süren apostil işlemlerini internet üzerinden çok kısa sürede yapabiliyor."
>>> len(text1)
138
</code>

== 2.Metindeki kelime sayısını bulmak ==
<code python>
>>> text2 = text1.split(' ')
>>> len(text2)
18
>>>text2
['Yurt', 'dışında', 'yaşayan', 'vatandaşlarımız,', 'daha', 'önce', 'zahmetli', 've', 'uzun', 'süren', 'apostil', 'işlemlerini', 'internet', 'üzerinden', 'çok', 'kısa', 'sürede', 'yapabiliyor.']
</code>

== 3.Belirli kelimeleri bulma ===
text2'de 3 harften uzun kelimeleri bulmak
<code python>
>>> [w for w in text2 if len(w) > 3]
['Yurt', 'dışında', 'yaşayan', 'vatandaşlarımız,', 'daha', 'önce', 'zahmetli', 'uzun', 'süren', 'apostil', 'işlemlerini', 'internet', 'üzerinden', 'kısa', 'sürede', 'yapabiliyor.']
</code>

text2'de büyük harfle başlayan kelimeleri bulmak
<code python>
>>> [w for w in text2 if w.istitle()]
['Yurt']
</code>

text2'de e ile biten kelimeleri bulmak
<code python>
>>> [w for w in text2 if w.endswith('e')]
['önce', 've', 'sürede']
</code>

Benzersiz kelimeleri 'set()' kullanarak bulmak

<code python>
>>> text3 = "Dal sarkar kartal kalkar, kartal kalkar dal sarkar"
>>> text4 = text3.split(' ')
>>> len(text4)
8
>>> len(set(text4))
6
>>> set(text4)
{'kalkar,', 'sarkar', 'kalkar', 'kartal', 'Dal', 'dal'}
>>> len(set([w.lower() for w in text4])) # .lower tüm stringleri küçük harfe çevirir
5
>>> set([w.lower() for w in text4])
{'kalkar,', 'sarkar', 'kalkar', 'kartal', 'dal'}
</code>
== 4.Serbest metin işleme ==
<code python>
>>> text5 = 'İdari Yargının Etkinliğinin Artırılması ve Danıştay’ın Kurumsal Kapasitesinin Güçlendirilmesi Projesi’nin 3. Yürütme Kurulu toplantısı Sn. Hakan Öztatar’ın başkanlığında 19/06/2020 tarihinde video konferans yoluyla gerçekleştirilmiştir #ABProjeleri #OrtakGelecegimiz @ABBaskanligi https://twitter.com/higm_adalet'
>>> text6 = text5.split(' ')
>>>
>>> text6
['İdari', 'Yargının', 'Etkinliğinin', 'Artırılması', 've', 'Danıştay’ın', 'Kurumsal', 'Kapasitesinin', 'Güçlendirilmesi', 'Projesi’nin', '3.', 'Yürütme', 'Kurulu', 'toplantısı', 'Sn.', 'Hakan', 'Öztatar’ın', 'başkanlığında', '19/06/2020', 'tarihinde', 'video', 'konferans', 'yoluyla', 'gerçekleştirilmiştir', '#ABProjeleri', '#OrtakGelecegimiz', '@ABBaskanligi', 'https://twitter.com/higm_adalet']
</code>

Hashtagleri bulmak

<code python>
>>> [w for w in text6 if w.startswith('#')]
['#ABProjeleri', '#OrtakGelecegimiz']
</code>

Bahsetmeleri(callout) bulmak

<code python>
>>> [w for w in text6 if w.startswith('@')]
['@ABBaskanligi']
</code>

== 5.Regular Expressionları(regex) kullanarak metin işleme ==

<code python>
>>> text7 = "Avrupa Bölgeler ve Şehirler Haftası bu yıl ilk kez pandemi nedeniyle dijital olarak düzenlenecek. 5-22 Ekim 2020 tarihlerindeki etkinliklere 27 Eylül 2020’ye kadar kayıt yaptırabilirsiniz. #EURegionsWeek #interreg #cbc #cbcbgtr #cbcbsb #enicbc #solidaritycorps #H2020 @EUgreendeal"
>>> text8 = text7.split(' ')
>>> text8
['Avrupa', 'Bölgeler', 've', 'Şehirler', 'Haftası', 'bu', 'yıl', 'ilk', 'kez', 'pandemi', 'nedeniyle', 'dijital', 'olarak', 'düzenlenecek.', '5-22', 'Ekim', '2020', 'tarihlerindeki', 'etkinliklere', '27', 'Eylül', '2020’ye', 'kadar', 'kayıt', 'yaptırabilirsiniz.', '#EURegionsWeek', '#interreg', '#cbc', '#cbcbgtr', '#cbcbsb', '#enicbc', '#solidaritycorps', '#H2020', '@EUgreendeal']
</code>
Regular expressionları kullanarak daha gelişmiş string parse etme işlemleri yapabliriz.

Örneğin `'@[A-Za-z0-9_]+'` ifadesinin döndüreceği tüm kelimelerin özellikleri şu şekilde olacaktır:
- `'@'` ile başlar ve en az aşağadaki özelliklerin birine sahiptir:
  * Büyük harfler (`'A-Z'`)
  * Küçük harfler (`'a-z'`)
  * Sayılar (`'0-9'`)
  * veya alt tire (`'_'`)

<code python>
import re
>>> [w for w in text8 if re.search('@[A-Za-z0-9_]+', w)]
['@EUgreendeal']
</code>
